/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICrossChainCounterInterface extends Interface {
  getFunction(nameOrSignature: "receiveIncrementCommand"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CounterIncremented"
      | "SupportedChainAdded"
      | "SupportedChainRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "receiveIncrementCommand",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveIncrementCommand",
    data: BytesLike
  ): Result;
}

export namespace CounterIncrementedEvent {
  export type InputTuple = [
    newCounterValue: BigNumberish,
    amount: BigNumberish,
    chainFrom: BigNumberish,
    initiator: AddressLike
  ];
  export type OutputTuple = [
    newCounterValue: bigint,
    amount: bigint,
    chainFrom: bigint,
    initiator: string
  ];
  export interface OutputObject {
    newCounterValue: bigint;
    amount: bigint;
    chainFrom: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedChainAddedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    incrementorAddress: BytesLike
  ];
  export type OutputTuple = [chainId: bigint, incrementorAddress: string];
  export interface OutputObject {
    chainId: bigint;
    incrementorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupportedChainRemovedEvent {
  export type InputTuple = [chainId: BigNumberish];
  export type OutputTuple = [chainId: bigint];
  export interface OutputObject {
    chainId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICrossChainCounter extends BaseContract {
  connect(runner?: ContractRunner | null): ICrossChainCounter;
  waitForDeployment(): Promise<this>;

  interface: ICrossChainCounterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  receiveIncrementCommand: TypedContractMethod<
    [_amount: BigNumberish, _initiator: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "receiveIncrementCommand"
  ): TypedContractMethod<
    [_amount: BigNumberish, _initiator: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CounterIncremented"
  ): TypedContractEvent<
    CounterIncrementedEvent.InputTuple,
    CounterIncrementedEvent.OutputTuple,
    CounterIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedChainAdded"
  ): TypedContractEvent<
    SupportedChainAddedEvent.InputTuple,
    SupportedChainAddedEvent.OutputTuple,
    SupportedChainAddedEvent.OutputObject
  >;
  getEvent(
    key: "SupportedChainRemoved"
  ): TypedContractEvent<
    SupportedChainRemovedEvent.InputTuple,
    SupportedChainRemovedEvent.OutputTuple,
    SupportedChainRemovedEvent.OutputObject
  >;

  filters: {
    "CounterIncremented(uint256,uint8,uint256,address)": TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;
    CounterIncremented: TypedContractEvent<
      CounterIncrementedEvent.InputTuple,
      CounterIncrementedEvent.OutputTuple,
      CounterIncrementedEvent.OutputObject
    >;

    "SupportedChainAdded(uint256,bytes)": TypedContractEvent<
      SupportedChainAddedEvent.InputTuple,
      SupportedChainAddedEvent.OutputTuple,
      SupportedChainAddedEvent.OutputObject
    >;
    SupportedChainAdded: TypedContractEvent<
      SupportedChainAddedEvent.InputTuple,
      SupportedChainAddedEvent.OutputTuple,
      SupportedChainAddedEvent.OutputObject
    >;

    "SupportedChainRemoved(uint256)": TypedContractEvent<
      SupportedChainRemovedEvent.InputTuple,
      SupportedChainRemovedEvent.OutputTuple,
      SupportedChainRemovedEvent.OutputObject
    >;
    SupportedChainRemoved: TypedContractEvent<
      SupportedChainRemovedEvent.InputTuple,
      SupportedChainRemovedEvent.OutputTuple,
      SupportedChainRemovedEvent.OutputObject
    >;
  };
}
