/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SignatureUtil,
  SignatureUtilInterface,
} from "../../../../../@debridge-finance/contracts/contracts/libraries/SignatureUtil";

const _abi = [
  {
    inputs: [],
    name: "SignatureInvalidLength",
    type: "error",
  },
  {
    inputs: [],
    name: "SignatureInvalidV",
    type: "error",
  },
  {
    inputs: [],
    name: "WrongArgumentLength",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220591dd9dc4aa104777fa372fe062598a46203f080f67fa423fe3c77dce5226faa64736f6c63430008070033";

type SignatureUtilConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SignatureUtilConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SignatureUtil__factory extends ContractFactory {
  constructor(...args: SignatureUtilConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SignatureUtil & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SignatureUtil__factory {
    return super.connect(runner) as SignatureUtil__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SignatureUtilInterface {
    return new Interface(_abi) as SignatureUtilInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SignatureUtil {
    return new Contract(address, _abi, runner) as unknown as SignatureUtil;
  }
}
