/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export declare namespace IDeBridgeGate {
  export type ChainSupportInfoStruct = {
    fixedNativeFee: BigNumberish;
    isSupported: boolean;
    transferFeeBps: BigNumberish;
  };

  export type ChainSupportInfoStructOutput = [
    fixedNativeFee: bigint,
    isSupported: boolean,
    transferFeeBps: bigint
  ] & { fixedNativeFee: bigint; isSupported: boolean; transferFeeBps: bigint };

  export type FeeParamsStruct = {
    receivedAmount: BigNumberish;
    fixFee: BigNumberish;
    transferFee: BigNumberish;
    useAssetFee: boolean;
    isNativeToken: boolean;
  };

  export type FeeParamsStructOutput = [
    receivedAmount: bigint,
    fixFee: bigint,
    transferFee: bigint,
    useAssetFee: boolean,
    isNativeToken: boolean
  ] & {
    receivedAmount: bigint;
    fixFee: bigint;
    transferFee: bigint;
    useAssetFee: boolean;
    isNativeToken: boolean;
  };
}

export interface IDeBridgeGateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "flash"
      | "getDebridgeChainAssetFixedFee"
      | "getDefiAvaliableReserves"
      | "getNativeInfo"
      | "isSubmissionUsed"
      | "requestReserves"
      | "returnReserves"
      | "send"
      | "withdrawFee"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutoRequestExecuted"
      | "Blocked"
      | "CallProxyUpdated"
      | "ChainSupportUpdated"
      | "ChainsSupportUpdated"
      | "Claimed"
      | "FixedNativeFeeAutoUpdated"
      | "FixedNativeFeeUpdated"
      | "Flash"
      | "MonitoringClaimEvent"
      | "MonitoringSendEvent"
      | "PairAdded"
      | "Sent"
      | "Unblocked"
      | "WithdrawnFee"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flash",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebridgeChainAssetFixedFee",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDefiAvaliableReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNativeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubmissionUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestReserves",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "returnReserves",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "send",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      boolean,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFee",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "flash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDebridgeChainAssetFixedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDefiAvaliableReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNativeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubmissionUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "returnReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "send", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFee",
    data: BytesLike
  ): Result;
}

export namespace AutoRequestExecutedEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    success: boolean,
    callProxy: AddressLike
  ];
  export type OutputTuple = [
    submissionId: string,
    success: boolean,
    callProxy: string
  ];
  export interface OutputObject {
    submissionId: string;
    success: boolean;
    callProxy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlockedEvent {
  export type InputTuple = [submissionId: BytesLike];
  export type OutputTuple = [submissionId: string];
  export interface OutputObject {
    submissionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CallProxyUpdatedEvent {
  export type InputTuple = [callProxy: AddressLike];
  export type OutputTuple = [callProxy: string];
  export interface OutputObject {
    callProxy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainSupportUpdatedEvent {
  export type InputTuple = [
    chainId: BigNumberish,
    isSupported: boolean,
    isChainFrom: boolean
  ];
  export type OutputTuple = [
    chainId: bigint,
    isSupported: boolean,
    isChainFrom: boolean
  ];
  export interface OutputObject {
    chainId: bigint;
    isSupported: boolean;
    isChainFrom: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainsSupportUpdatedEvent {
  export type InputTuple = [
    chainIds: BigNumberish,
    chainSupportInfo: IDeBridgeGate.ChainSupportInfoStruct,
    isChainFrom: boolean
  ];
  export type OutputTuple = [
    chainIds: bigint,
    chainSupportInfo: IDeBridgeGate.ChainSupportInfoStructOutput,
    isChainFrom: boolean
  ];
  export interface OutputObject {
    chainIds: bigint;
    chainSupportInfo: IDeBridgeGate.ChainSupportInfoStructOutput;
    isChainFrom: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimedEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    debridgeId: BytesLike,
    amount: BigNumberish,
    receiver: AddressLike,
    nonce: BigNumberish,
    chainIdFrom: BigNumberish,
    autoParams: BytesLike,
    isNativeToken: boolean
  ];
  export type OutputTuple = [
    submissionId: string,
    debridgeId: string,
    amount: bigint,
    receiver: string,
    nonce: bigint,
    chainIdFrom: bigint,
    autoParams: string,
    isNativeToken: boolean
  ];
  export interface OutputObject {
    submissionId: string;
    debridgeId: string;
    amount: bigint;
    receiver: string;
    nonce: bigint;
    chainIdFrom: bigint;
    autoParams: string;
    isNativeToken: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FixedNativeFeeAutoUpdatedEvent {
  export type InputTuple = [globalFixedNativeFee: BigNumberish];
  export type OutputTuple = [globalFixedNativeFee: bigint];
  export interface OutputObject {
    globalFixedNativeFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FixedNativeFeeUpdatedEvent {
  export type InputTuple = [
    globalFixedNativeFee: BigNumberish,
    globalTransferFeeBps: BigNumberish
  ];
  export type OutputTuple = [
    globalFixedNativeFee: bigint,
    globalTransferFeeBps: bigint
  ];
  export interface OutputObject {
    globalFixedNativeFee: bigint;
    globalTransferFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashEvent {
  export type InputTuple = [
    sender: AddressLike,
    tokenAddress: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish,
    paid: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    tokenAddress: string,
    receiver: string,
    amount: bigint,
    paid: bigint
  ];
  export interface OutputObject {
    sender: string;
    tokenAddress: string;
    receiver: string;
    amount: bigint;
    paid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonitoringClaimEventEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    lockedOrMintedAmount: BigNumberish,
    totalSupply: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: string,
    lockedOrMintedAmount: bigint,
    totalSupply: bigint
  ];
  export interface OutputObject {
    submissionId: string;
    lockedOrMintedAmount: bigint;
    totalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MonitoringSendEventEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    nonce: BigNumberish,
    lockedOrMintedAmount: BigNumberish,
    totalSupply: BigNumberish
  ];
  export type OutputTuple = [
    submissionId: string,
    nonce: bigint,
    lockedOrMintedAmount: bigint,
    totalSupply: bigint
  ];
  export interface OutputObject {
    submissionId: string;
    nonce: bigint;
    lockedOrMintedAmount: bigint;
    totalSupply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PairAddedEvent {
  export type InputTuple = [
    debridgeId: BytesLike,
    tokenAddress: AddressLike,
    nativeAddress: BytesLike,
    nativeChainId: BigNumberish,
    maxAmount: BigNumberish,
    minReservesBps: BigNumberish
  ];
  export type OutputTuple = [
    debridgeId: string,
    tokenAddress: string,
    nativeAddress: string,
    nativeChainId: bigint,
    maxAmount: bigint,
    minReservesBps: bigint
  ];
  export interface OutputObject {
    debridgeId: string;
    tokenAddress: string;
    nativeAddress: string;
    nativeChainId: bigint;
    maxAmount: bigint;
    minReservesBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SentEvent {
  export type InputTuple = [
    submissionId: BytesLike,
    debridgeId: BytesLike,
    amount: BigNumberish,
    receiver: BytesLike,
    nonce: BigNumberish,
    chainIdTo: BigNumberish,
    referralCode: BigNumberish,
    feeParams: IDeBridgeGate.FeeParamsStruct,
    autoParams: BytesLike,
    nativeSender: AddressLike
  ];
  export type OutputTuple = [
    submissionId: string,
    debridgeId: string,
    amount: bigint,
    receiver: string,
    nonce: bigint,
    chainIdTo: bigint,
    referralCode: bigint,
    feeParams: IDeBridgeGate.FeeParamsStructOutput,
    autoParams: string,
    nativeSender: string
  ];
  export interface OutputObject {
    submissionId: string;
    debridgeId: string;
    amount: bigint;
    receiver: string;
    nonce: bigint;
    chainIdTo: bigint;
    referralCode: bigint;
    feeParams: IDeBridgeGate.FeeParamsStructOutput;
    autoParams: string;
    nativeSender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnblockedEvent {
  export type InputTuple = [submissionId: BytesLike];
  export type OutputTuple = [submissionId: string];
  export interface OutputObject {
    submissionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnFeeEvent {
  export type InputTuple = [debridgeId: BytesLike, fee: BigNumberish];
  export type OutputTuple = [debridgeId: string, fee: bigint];
  export interface OutputObject {
    debridgeId: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDeBridgeGate extends BaseContract {
  connect(runner?: ContractRunner | null): IDeBridgeGate;
  waitForDeployment(): Promise<this>;

  interface: IDeBridgeGateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [
      _debridgeId: BytesLike,
      _amount: BigNumberish,
      _chainIdFrom: BigNumberish,
      _receiver: AddressLike,
      _nonce: BigNumberish,
      _signatures: BytesLike,
      _autoParams: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  flash: TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDebridgeChainAssetFixedFee: TypedContractMethod<
    [_debridgeId: BytesLike, _chainId: BigNumberish],
    [bigint],
    "view"
  >;

  getDefiAvaliableReserves: TypedContractMethod<
    [_tokenAddress: AddressLike],
    [bigint],
    "view"
  >;

  getNativeInfo: TypedContractMethod<
    [token: AddressLike],
    [[bigint, string] & { nativeChainId: bigint; nativeAddress: string }],
    "nonpayable"
  >;

  isSubmissionUsed: TypedContractMethod<
    [submissionId: BytesLike],
    [boolean],
    "nonpayable"
  >;

  requestReserves: TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  returnReserves: TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  send: TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _amount: BigNumberish,
      _chainIdTo: BigNumberish,
      _receiver: BytesLike,
      _permit: BytesLike,
      _useAssetFee: boolean,
      _referralCode: BigNumberish,
      _autoParams: BytesLike
    ],
    [void],
    "payable"
  >;

  withdrawFee: TypedContractMethod<
    [_debridgeId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      _debridgeId: BytesLike,
      _amount: BigNumberish,
      _chainIdFrom: BigNumberish,
      _receiver: AddressLike,
      _nonce: BigNumberish,
      _signatures: BytesLike,
      _autoParams: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flash"
  ): TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _receiver: AddressLike,
      _amount: BigNumberish,
      _data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDebridgeChainAssetFixedFee"
  ): TypedContractMethod<
    [_debridgeId: BytesLike, _chainId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDefiAvaliableReserves"
  ): TypedContractMethod<[_tokenAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNativeInfo"
  ): TypedContractMethod<
    [token: AddressLike],
    [[bigint, string] & { nativeChainId: bigint; nativeAddress: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isSubmissionUsed"
  ): TypedContractMethod<[submissionId: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "requestReserves"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "returnReserves"
  ): TypedContractMethod<
    [_tokenAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "send"
  ): TypedContractMethod<
    [
      _tokenAddress: AddressLike,
      _amount: BigNumberish,
      _chainIdTo: BigNumberish,
      _receiver: BytesLike,
      _permit: BytesLike,
      _useAssetFee: boolean,
      _referralCode: BigNumberish,
      _autoParams: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawFee"
  ): TypedContractMethod<[_debridgeId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AutoRequestExecuted"
  ): TypedContractEvent<
    AutoRequestExecutedEvent.InputTuple,
    AutoRequestExecutedEvent.OutputTuple,
    AutoRequestExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Blocked"
  ): TypedContractEvent<
    BlockedEvent.InputTuple,
    BlockedEvent.OutputTuple,
    BlockedEvent.OutputObject
  >;
  getEvent(
    key: "CallProxyUpdated"
  ): TypedContractEvent<
    CallProxyUpdatedEvent.InputTuple,
    CallProxyUpdatedEvent.OutputTuple,
    CallProxyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ChainSupportUpdated"
  ): TypedContractEvent<
    ChainSupportUpdatedEvent.InputTuple,
    ChainSupportUpdatedEvent.OutputTuple,
    ChainSupportUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ChainsSupportUpdated"
  ): TypedContractEvent<
    ChainsSupportUpdatedEvent.InputTuple,
    ChainsSupportUpdatedEvent.OutputTuple,
    ChainsSupportUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FixedNativeFeeAutoUpdated"
  ): TypedContractEvent<
    FixedNativeFeeAutoUpdatedEvent.InputTuple,
    FixedNativeFeeAutoUpdatedEvent.OutputTuple,
    FixedNativeFeeAutoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FixedNativeFeeUpdated"
  ): TypedContractEvent<
    FixedNativeFeeUpdatedEvent.InputTuple,
    FixedNativeFeeUpdatedEvent.OutputTuple,
    FixedNativeFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Flash"
  ): TypedContractEvent<
    FlashEvent.InputTuple,
    FlashEvent.OutputTuple,
    FlashEvent.OutputObject
  >;
  getEvent(
    key: "MonitoringClaimEvent"
  ): TypedContractEvent<
    MonitoringClaimEventEvent.InputTuple,
    MonitoringClaimEventEvent.OutputTuple,
    MonitoringClaimEventEvent.OutputObject
  >;
  getEvent(
    key: "MonitoringSendEvent"
  ): TypedContractEvent<
    MonitoringSendEventEvent.InputTuple,
    MonitoringSendEventEvent.OutputTuple,
    MonitoringSendEventEvent.OutputObject
  >;
  getEvent(
    key: "PairAdded"
  ): TypedContractEvent<
    PairAddedEvent.InputTuple,
    PairAddedEvent.OutputTuple,
    PairAddedEvent.OutputObject
  >;
  getEvent(
    key: "Sent"
  ): TypedContractEvent<
    SentEvent.InputTuple,
    SentEvent.OutputTuple,
    SentEvent.OutputObject
  >;
  getEvent(
    key: "Unblocked"
  ): TypedContractEvent<
    UnblockedEvent.InputTuple,
    UnblockedEvent.OutputTuple,
    UnblockedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnFee"
  ): TypedContractEvent<
    WithdrawnFeeEvent.InputTuple,
    WithdrawnFeeEvent.OutputTuple,
    WithdrawnFeeEvent.OutputObject
  >;

  filters: {
    "AutoRequestExecuted(bytes32,bool,address)": TypedContractEvent<
      AutoRequestExecutedEvent.InputTuple,
      AutoRequestExecutedEvent.OutputTuple,
      AutoRequestExecutedEvent.OutputObject
    >;
    AutoRequestExecuted: TypedContractEvent<
      AutoRequestExecutedEvent.InputTuple,
      AutoRequestExecutedEvent.OutputTuple,
      AutoRequestExecutedEvent.OutputObject
    >;

    "Blocked(bytes32)": TypedContractEvent<
      BlockedEvent.InputTuple,
      BlockedEvent.OutputTuple,
      BlockedEvent.OutputObject
    >;
    Blocked: TypedContractEvent<
      BlockedEvent.InputTuple,
      BlockedEvent.OutputTuple,
      BlockedEvent.OutputObject
    >;

    "CallProxyUpdated(address)": TypedContractEvent<
      CallProxyUpdatedEvent.InputTuple,
      CallProxyUpdatedEvent.OutputTuple,
      CallProxyUpdatedEvent.OutputObject
    >;
    CallProxyUpdated: TypedContractEvent<
      CallProxyUpdatedEvent.InputTuple,
      CallProxyUpdatedEvent.OutputTuple,
      CallProxyUpdatedEvent.OutputObject
    >;

    "ChainSupportUpdated(uint256,bool,bool)": TypedContractEvent<
      ChainSupportUpdatedEvent.InputTuple,
      ChainSupportUpdatedEvent.OutputTuple,
      ChainSupportUpdatedEvent.OutputObject
    >;
    ChainSupportUpdated: TypedContractEvent<
      ChainSupportUpdatedEvent.InputTuple,
      ChainSupportUpdatedEvent.OutputTuple,
      ChainSupportUpdatedEvent.OutputObject
    >;

    "ChainsSupportUpdated(uint256,tuple,bool)": TypedContractEvent<
      ChainsSupportUpdatedEvent.InputTuple,
      ChainsSupportUpdatedEvent.OutputTuple,
      ChainsSupportUpdatedEvent.OutputObject
    >;
    ChainsSupportUpdated: TypedContractEvent<
      ChainsSupportUpdatedEvent.InputTuple,
      ChainsSupportUpdatedEvent.OutputTuple,
      ChainsSupportUpdatedEvent.OutputObject
    >;

    "Claimed(bytes32,bytes32,uint256,address,uint256,uint256,bytes,bool)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "FixedNativeFeeAutoUpdated(uint256)": TypedContractEvent<
      FixedNativeFeeAutoUpdatedEvent.InputTuple,
      FixedNativeFeeAutoUpdatedEvent.OutputTuple,
      FixedNativeFeeAutoUpdatedEvent.OutputObject
    >;
    FixedNativeFeeAutoUpdated: TypedContractEvent<
      FixedNativeFeeAutoUpdatedEvent.InputTuple,
      FixedNativeFeeAutoUpdatedEvent.OutputTuple,
      FixedNativeFeeAutoUpdatedEvent.OutputObject
    >;

    "FixedNativeFeeUpdated(uint256,uint256)": TypedContractEvent<
      FixedNativeFeeUpdatedEvent.InputTuple,
      FixedNativeFeeUpdatedEvent.OutputTuple,
      FixedNativeFeeUpdatedEvent.OutputObject
    >;
    FixedNativeFeeUpdated: TypedContractEvent<
      FixedNativeFeeUpdatedEvent.InputTuple,
      FixedNativeFeeUpdatedEvent.OutputTuple,
      FixedNativeFeeUpdatedEvent.OutputObject
    >;

    "Flash(address,address,address,uint256,uint256)": TypedContractEvent<
      FlashEvent.InputTuple,
      FlashEvent.OutputTuple,
      FlashEvent.OutputObject
    >;
    Flash: TypedContractEvent<
      FlashEvent.InputTuple,
      FlashEvent.OutputTuple,
      FlashEvent.OutputObject
    >;

    "MonitoringClaimEvent(bytes32,uint256,uint256)": TypedContractEvent<
      MonitoringClaimEventEvent.InputTuple,
      MonitoringClaimEventEvent.OutputTuple,
      MonitoringClaimEventEvent.OutputObject
    >;
    MonitoringClaimEvent: TypedContractEvent<
      MonitoringClaimEventEvent.InputTuple,
      MonitoringClaimEventEvent.OutputTuple,
      MonitoringClaimEventEvent.OutputObject
    >;

    "MonitoringSendEvent(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      MonitoringSendEventEvent.InputTuple,
      MonitoringSendEventEvent.OutputTuple,
      MonitoringSendEventEvent.OutputObject
    >;
    MonitoringSendEvent: TypedContractEvent<
      MonitoringSendEventEvent.InputTuple,
      MonitoringSendEventEvent.OutputTuple,
      MonitoringSendEventEvent.OutputObject
    >;

    "PairAdded(bytes32,address,bytes,uint256,uint256,uint16)": TypedContractEvent<
      PairAddedEvent.InputTuple,
      PairAddedEvent.OutputTuple,
      PairAddedEvent.OutputObject
    >;
    PairAdded: TypedContractEvent<
      PairAddedEvent.InputTuple,
      PairAddedEvent.OutputTuple,
      PairAddedEvent.OutputObject
    >;

    "Sent(bytes32,bytes32,uint256,bytes,uint256,uint256,uint32,tuple,bytes,address)": TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;
    Sent: TypedContractEvent<
      SentEvent.InputTuple,
      SentEvent.OutputTuple,
      SentEvent.OutputObject
    >;

    "Unblocked(bytes32)": TypedContractEvent<
      UnblockedEvent.InputTuple,
      UnblockedEvent.OutputTuple,
      UnblockedEvent.OutputObject
    >;
    Unblocked: TypedContractEvent<
      UnblockedEvent.InputTuple,
      UnblockedEvent.OutputTuple,
      UnblockedEvent.OutputObject
    >;

    "WithdrawnFee(bytes32,uint256)": TypedContractEvent<
      WithdrawnFeeEvent.InputTuple,
      WithdrawnFeeEvent.OutputTuple,
      WithdrawnFeeEvent.OutputObject
    >;
    WithdrawnFee: TypedContractEvent<
      WithdrawnFeeEvent.InputTuple,
      WithdrawnFeeEvent.OutputTuple,
      WithdrawnFeeEvent.OutputObject
    >;
  };
}
