/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICallProxy } from "./ICallProxy";
export type { IDeBridgeGate } from "./IDeBridgeGate";
export type { IDeBridgeToken } from "./IDeBridgeToken";
export type { IDeBridgeTokenDeployer } from "./IDeBridgeTokenDeployer";
export type { IERC20Permit } from "./IERC20Permit";
export type { IFlashCallback } from "./IFlashCallback";
export type { IOraclesManager } from "./IOraclesManager";
export type { ISignatureVerifier } from "./ISignatureVerifier";
export type { IWETH } from "./IWETH";
export type { IWethGate } from "./IWethGate";
