/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDeBridgeTokenDeployer,
  IDeBridgeTokenDeployerInterface,
} from "../../../../../@debridge-finance/contracts/contracts/interfaces/IDeBridgeTokenDeployer";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "decimals",
        type: "uint8",
      },
    ],
    name: "DeBridgeTokenDeployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_debridgeId",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_symbol",
        type: "string",
      },
      {
        internalType: "uint8",
        name: "_decimals",
        type: "uint8",
      },
    ],
    name: "deployAsset",
    outputs: [
      {
        internalType: "address",
        name: "deTokenAddress",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDeBridgeTokenDeployer__factory {
  static readonly abi = _abi;
  static createInterface(): IDeBridgeTokenDeployerInterface {
    return new Interface(_abi) as IDeBridgeTokenDeployerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDeBridgeTokenDeployer {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDeBridgeTokenDeployer;
  }
}
