/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFlashCallback,
  IFlashCallbackInterface,
} from "../../../../../@debridge-finance/contracts/contracts/interfaces/IFlashCallback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "flashCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFlashCallback__factory {
  static readonly abi = _abi;
  static createInterface(): IFlashCallbackInterface {
    return new Interface(_abi) as IFlashCallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IFlashCallback {
    return new Contract(address, _abi, runner) as unknown as IFlashCallback;
  }
}
