/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISignatureVerifier,
  ISignatureVerifierInterface,
} from "../../../../../@debridge-finance/contracts/contracts/interfaces/ISignatureVerifier";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "submissionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "Confirmed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes32",
        name: "deployId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "DeployConfirmed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_submissionId",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "_signatures",
        type: "bytes",
      },
      {
        internalType: "uint8",
        name: "_excessConfirmations",
        type: "uint8",
      },
    ],
    name: "submit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISignatureVerifier__factory {
  static readonly abi = _abi;
  static createInterface(): ISignatureVerifierInterface {
    return new Interface(_abi) as ISignatureVerifierInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISignatureVerifier {
    return new Contract(address, _abi, runner) as unknown as ISignatureVerifier;
  }
}
