/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface SignatureVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "addOracles"
      | "confirmationThreshold"
      | "currentBlock"
      | "debridgeAddress"
      | "excessConfirmations"
      | "getOracleInfo"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isValidSignature"
      | "minConfirmations"
      | "oracleAddresses"
      | "renounceRole"
      | "requiredOraclesCount"
      | "revokeRole"
      | "setDebridgeAddress"
      | "setExcessConfirmations"
      | "setMinConfirmations"
      | "setThreshold"
      | "submissionsInBlock"
      | "submit"
      | "supportsInterface"
      | "updateOracle"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddOracle"
      | "Confirmed"
      | "DeployApproved"
      | "DeployConfirmed"
      | "Initialized"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "SubmissionApproved"
      | "UpdateOracle"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addOracles",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmationThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "debridgeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "excessConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOracleInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "minConfirmations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "oracleAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredOraclesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDebridgeAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExcessConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionsInBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submit",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOracle",
    values: [AddressLike, boolean, boolean]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addOracles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmationThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "excessConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOracleInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredOraclesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDebridgeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExcessConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionsInBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AddOracleEvent {
  export type InputTuple = [oracle: AddressLike, required: boolean];
  export type OutputTuple = [oracle: string, required: boolean];
  export interface OutputObject {
    oracle: string;
    required: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfirmedEvent {
  export type InputTuple = [submissionId: BytesLike, operator: AddressLike];
  export type OutputTuple = [submissionId: string, operator: string];
  export interface OutputObject {
    submissionId: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployApprovedEvent {
  export type InputTuple = [deployId: BytesLike];
  export type OutputTuple = [deployId: string];
  export interface OutputObject {
    deployId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeployConfirmedEvent {
  export type InputTuple = [deployId: BytesLike, operator: AddressLike];
  export type OutputTuple = [deployId: string, operator: string];
  export interface OutputObject {
    deployId: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubmissionApprovedEvent {
  export type InputTuple = [submissionId: BytesLike];
  export type OutputTuple = [submissionId: string];
  export interface OutputObject {
    submissionId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdateOracleEvent {
  export type InputTuple = [
    oracle: AddressLike,
    required: boolean,
    isValid: boolean
  ];
  export type OutputTuple = [
    oracle: string,
    required: boolean,
    isValid: boolean
  ];
  export interface OutputObject {
    oracle: string;
    required: boolean;
    isValid: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SignatureVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): SignatureVerifier;
  waitForDeployment(): Promise<this>;

  interface: SignatureVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  addOracles: TypedContractMethod<
    [_oracles: AddressLike[], _required: boolean[]],
    [void],
    "nonpayable"
  >;

  confirmationThreshold: TypedContractMethod<[], [bigint], "view">;

  currentBlock: TypedContractMethod<[], [bigint], "view">;

  debridgeAddress: TypedContractMethod<[], [string], "view">;

  excessConfirmations: TypedContractMethod<[], [bigint], "view">;

  getOracleInfo: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean] & {
        exist: boolean;
        isValid: boolean;
        required: boolean;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _minConfirmations: BigNumberish,
      _confirmationThreshold: BigNumberish,
      _excessConfirmations: BigNumberish,
      _debridgeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isValidSignature: TypedContractMethod<
    [_submissionId: BytesLike, _signature: BytesLike],
    [boolean],
    "view"
  >;

  minConfirmations: TypedContractMethod<[], [bigint], "view">;

  oracleAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredOraclesCount: TypedContractMethod<[], [bigint], "view">;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setDebridgeAddress: TypedContractMethod<
    [_debridgeAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setExcessConfirmations: TypedContractMethod<
    [_excessConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinConfirmations: TypedContractMethod<
    [_minConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;

  setThreshold: TypedContractMethod<
    [_confirmationThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  submissionsInBlock: TypedContractMethod<[], [bigint], "view">;

  submit: TypedContractMethod<
    [
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateOracle: TypedContractMethod<
    [_oracle: AddressLike, _isValid: boolean, _required: boolean],
    [void],
    "nonpayable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addOracles"
  ): TypedContractMethod<
    [_oracles: AddressLike[], _required: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confirmationThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "debridgeAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "excessConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOracleInfo"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, boolean, boolean] & {
        exist: boolean;
        isValid: boolean;
        required: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _minConfirmations: BigNumberish,
      _confirmationThreshold: BigNumberish,
      _excessConfirmations: BigNumberish,
      _debridgeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isValidSignature"
  ): TypedContractMethod<
    [_submissionId: BytesLike, _signature: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "minConfirmations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "oracleAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requiredOraclesCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDebridgeAddress"
  ): TypedContractMethod<[_debridgeAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExcessConfirmations"
  ): TypedContractMethod<
    [_excessConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinConfirmations"
  ): TypedContractMethod<
    [_minConfirmations: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setThreshold"
  ): TypedContractMethod<
    [_confirmationThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submissionsInBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submit"
  ): TypedContractMethod<
    [
      _submissionId: BytesLike,
      _signatures: BytesLike,
      _excessConfirmations: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateOracle"
  ): TypedContractMethod<
    [_oracle: AddressLike, _isValid: boolean, _required: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AddOracle"
  ): TypedContractEvent<
    AddOracleEvent.InputTuple,
    AddOracleEvent.OutputTuple,
    AddOracleEvent.OutputObject
  >;
  getEvent(
    key: "Confirmed"
  ): TypedContractEvent<
    ConfirmedEvent.InputTuple,
    ConfirmedEvent.OutputTuple,
    ConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "DeployApproved"
  ): TypedContractEvent<
    DeployApprovedEvent.InputTuple,
    DeployApprovedEvent.OutputTuple,
    DeployApprovedEvent.OutputObject
  >;
  getEvent(
    key: "DeployConfirmed"
  ): TypedContractEvent<
    DeployConfirmedEvent.InputTuple,
    DeployConfirmedEvent.OutputTuple,
    DeployConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SubmissionApproved"
  ): TypedContractEvent<
    SubmissionApprovedEvent.InputTuple,
    SubmissionApprovedEvent.OutputTuple,
    SubmissionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "UpdateOracle"
  ): TypedContractEvent<
    UpdateOracleEvent.InputTuple,
    UpdateOracleEvent.OutputTuple,
    UpdateOracleEvent.OutputObject
  >;

  filters: {
    "AddOracle(address,bool)": TypedContractEvent<
      AddOracleEvent.InputTuple,
      AddOracleEvent.OutputTuple,
      AddOracleEvent.OutputObject
    >;
    AddOracle: TypedContractEvent<
      AddOracleEvent.InputTuple,
      AddOracleEvent.OutputTuple,
      AddOracleEvent.OutputObject
    >;

    "Confirmed(bytes32,address)": TypedContractEvent<
      ConfirmedEvent.InputTuple,
      ConfirmedEvent.OutputTuple,
      ConfirmedEvent.OutputObject
    >;
    Confirmed: TypedContractEvent<
      ConfirmedEvent.InputTuple,
      ConfirmedEvent.OutputTuple,
      ConfirmedEvent.OutputObject
    >;

    "DeployApproved(bytes32)": TypedContractEvent<
      DeployApprovedEvent.InputTuple,
      DeployApprovedEvent.OutputTuple,
      DeployApprovedEvent.OutputObject
    >;
    DeployApproved: TypedContractEvent<
      DeployApprovedEvent.InputTuple,
      DeployApprovedEvent.OutputTuple,
      DeployApprovedEvent.OutputObject
    >;

    "DeployConfirmed(bytes32,address)": TypedContractEvent<
      DeployConfirmedEvent.InputTuple,
      DeployConfirmedEvent.OutputTuple,
      DeployConfirmedEvent.OutputObject
    >;
    DeployConfirmed: TypedContractEvent<
      DeployConfirmedEvent.InputTuple,
      DeployConfirmedEvent.OutputTuple,
      DeployConfirmedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "SubmissionApproved(bytes32)": TypedContractEvent<
      SubmissionApprovedEvent.InputTuple,
      SubmissionApprovedEvent.OutputTuple,
      SubmissionApprovedEvent.OutputObject
    >;
    SubmissionApproved: TypedContractEvent<
      SubmissionApprovedEvent.InputTuple,
      SubmissionApprovedEvent.OutputTuple,
      SubmissionApprovedEvent.OutputObject
    >;

    "UpdateOracle(address,bool,bool)": TypedContractEvent<
      UpdateOracleEvent.InputTuple,
      UpdateOracleEvent.OutputTuple,
      UpdateOracleEvent.OutputObject
    >;
    UpdateOracle: TypedContractEvent<
      UpdateOracleEvent.InputTuple,
      UpdateOracleEvent.OutputTuple,
      UpdateOracleEvent.OutputObject
    >;
  };
}
