/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICallProxy__factory } from "./ICallProxy__factory";
export { IDeBridgeGate__factory } from "./IDeBridgeGate__factory";
